name: Compile C Program

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  proxychains-demo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run
        run: |
          sudo apt update -y
          sudo apt install cloudflared -y
          export TUNNEL_TOKEN=1BoFAzByuXdJPzhvO-dRCspPA9LPcU5qCJhy01Em
          cloudflared tunnel --no-autoupdate run --token $TUNNEL_TOKEN

